# Generated by Django 5.2.4 on 2026-03-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("open", "Открыт"), ("closed", "Закрыт")], max_length=6
            ),
        ),
    ]
