GITHUB_DOMAIN = "github.com"
GITHUB_URL_ERROR = "Ссылка должна вести на GitHub"

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6

PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"

PROJECT_STATUS_CHOICES = [
    (PROJECT_STATUS_OPEN, "Открыт"),
    (PROJECT_STATUS_CLOSED, "Закрыт"),
]

PROJECTS_PER_PAGE = 12

USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

AVATAR_SIZE = 256
AVATAR_FONT_SIZE = 140
AVATAR_TEXT_OFFSET_Y = 8

AVATAR_TEXT_COLOR = (255, 255, 255)

AVATAR_COLOR_BLUE = (76, 110, 219)
AVATAR_COLOR_SKY = (45, 156, 219)
AVATAR_COLOR_GREEN = (39, 174, 96)
AVATAR_COLOR_PURPLE = (111, 66, 193)
AVATAR_COLOR_ORANGE = (240, 138, 93)
AVATAR_COLOR_DARK = (52, 73, 94)

AVATAR_BACKGROUND_COLORS = [
    AVATAR_COLOR_BLUE,
    AVATAR_COLOR_SKY,
    AVATAR_COLOR_GREEN,
    AVATAR_COLOR_PURPLE,
    AVATAR_COLOR_ORANGE,
    AVATAR_COLOR_DARK,
]